### ISSUE TITLE
openai service provided by the AppHost : An OpenAIClient could not be configured

### ISSUE THREAD

**Issue by rachkoud** [Azure-Samples/eShopLite-SemanticSearch#1]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
For Local development using an existing gpt-4o-mini and ada-002 model, we can use a user secret in `Products` and it works fine : 

```json
{
  "ConnectionStrings:openaidev": "Endpoint=https://<endpoint>.openai.azure.com/;Key=<key>;"
}
```

But I want to use the services provided by the AppHost, so I open the the `program.cs` and change this

```csharp
// Add Azure OpenAI client
var azureOpenAiClientName = builder.Environment.IsDevelopment() ? "openaidev" : "openai";
builder.AddAzureOpenAIClient(azureOpenAiClientName);
```

To this : 

```csharp
// Add Azure OpenAI client
var azureOpenAiClientName = "openai";
builder.AddAzureOpenAIClient(azureOpenAiClientName);
```

eShopAppHost has the default appsettings.json : 

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "Aspire.Hosting.Dcp": "Warning"
    }
  },
  "Azure": {
    "CredentialSource": "AzureCli"
  }
}
```

If I type `az account show` I can see that I'm connected: 

```json
{
  "environmentName": "AzureCloud",
  "homeTenantId": "xxx",
  "id": "xxx",
  "isDefault": true,
  "managedByTenants": [],
  "name": "xxx",
  "state": "Enabled",
  "tenantId": "xxx",
  "user": {
    "name": "x@x.com",
    "type": "user"
  }
}
```

Also with azd : 

```bash
azd auth login --check-status
Logged in to Azure.
```

openai ressource is configured correctly : 

![image](https://github.com/user-attachments/assets/955130f7-dba2-4d5e-979b-546d302cad5d)

But when I try to search a product with semantic search, I'm getting these exceptions : 

![image](https://github.com/user-attachments/assets/2eabedde-a0f8-485e-891a-57d5c69b25fd)

```csharp
System.InvalidOperationException: An OpenAIClient could not be configured. Ensure valid connection information was provided in 'ConnectionStrings:openai' or specify a 'Endpoint' or 'Key' in the 'Aspire:Azure:AI:OpenAI' configuration section.
   at Microsoft.Extensions.Hosting.AspireAzureOpenAIExtensions.OpenAIComponent.<>c__DisplayClass4_0.<AddClient>b__0(AzureOpenAIClientOptions options, TokenCredential _, IServiceProvider _) in /_/src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIExtensions.cs:line 87
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass14_0`2.<AddClient>b__0(TOptions options, TokenCredential credential, IServiceProvider provider)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass15_0`2.<RegisterClientFactory>b__0(IServiceProvider provider, Object options, TokenCredential credential)
   at Microsoft.Extensions.Azure.ClientRegistration`1.GetClient(IServiceProvider serviceProvider, Object options, TokenCredential tokenCredential)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Azure.ClientRegistration`1.TryGetCachedClientOrThrow(TClient& cachedClient)
   at Microsoft.Extensions.Azure.ClientRegistration`1.GetClient(IServiceProvider serviceProvider, Object options, TokenCredential tokenCredential)
   at Microsoft.Extensions.Azure.AzureClientFactory`2.CreateClient(String name)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__15`2.<RegisterClientFactory>b__15_1(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.AspireAzureOpenAIExtensions.<>c.<AddAzureOpenAIClient>b__1_0(IServiceProvider provider) in /_/src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIExtensions.cs:line 46
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Program.<>c.<<Main>$>b__0_1(IServiceProvider serviceProvider) in C:\dev\repos\eShopLite-SemanticSearch\src\Products\Program.cs:line 61
```

I have to create openai ConnectionString in the secrets of `Products` project? 

```json
{
  "ConnectionStrings:openai": "Endpoint=https://<endpoint>.openai.azure.com/;Key=<key>;"
}
```

But it should use the openai ressource defined in eShopAppHost project : 

```csharp
var aoai = builder.AddAzureOpenAI("openai")
    .AddDeployment(new AzureOpenAIDeployment(chatDeploymentName,
    "gpt-4o-mini",
    "2024-07-18",
    "GlobalStandard",
    10))
    .AddDeployment(new AzureOpenAIDeployment(embeddingsDeploymentName,
    "text-embedding-ada-002",
    "2"));
```

The openai endpoint has been created with disableLocalAuth 

![image](https://github.com/user-attachments/assets/9ed31efa-40c1-4cda-8f37-1c88dd3cb102)

Thanks for support.

Also huge big up to @elbruno which is doing an awesome job with .NET and AI !!

**Comment by rachkoud** [comment]
When I was closed to finish writing my issue, I saw this comment : 

```csharp
// check if working in dev environment
// remove the if, if you want to use the references also in development
if (!builder.Environment.IsDevelopment())
{
    products.WithReference(aoai)
    .WithEnvironment("AI_ChatDeploymentName", chatDeploymentName)
    .WithEnvironment("AI_embeddingsDeploymentName", embeddingsDeploymentName);
}
```

Just remove the if and use it like this : 

```csharp
  products.WithReference(aoai)
  .WithEnvironment("AI_ChatDeploymentName", chatDeploymentName)
  .WithEnvironment("AI_embeddingsDeploymentName", embeddingsDeploymentName);
```

And it works fine!

I left the issue so someone could find it.

But you can adapt the documentation [Local development using an existing gpt-4o-mini and ada-002 model](https://github.com/Azure-Samples/eShopLite-SemanticSearch#local-development-using-an-existing-gpt-4o-mini-and-ada-002-model) and add this information.
